steps:
  - simple_align:
      cases: false
      top_level_patterns: false
      records: false
      multi_way_if: false
  - imports:
      align: none
      list_align: after_alias
      pad_module_names: false
      long_list_align: new_line
      empty_list_align: inherit
      list_padding: 2
      separate_lists: false
      space_surround: false
      post_qualify: true
  - trailing_whitespace: {}
columns: 100
newline: native
language_extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - DeriveTraversable
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
