# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1000
  directories:
  - $HOME/.stack
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- mkdir -p $HOME/.sbt/launchers/1.2.3/
- export PATH=$HOME/.local/bin:$PATH
# Download and unpack the stack executable
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Download sbt
- travis_retry curl -L https://github.com/sbt/sbt/releases/download/v1.2.8/sbt-1.2.8.tgz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/sbt'
- travis_retry curl -L -o $HOME/.sbt/launchers/1.2.3/sbt-launch.jar https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.3/sbt-launch.jar
# Download and compile flatbuffers
- git clone https://github.com/google/flatbuffers.git $HOME/flatbuffers
- cd $HOME/flatbuffers
- git checkout 129ef422e8a4e89d87a7216a865602673a6d0bf3
- cmake -G "Unix Makefiles"
- make
- cp flatc ~/.local/bin
- cd -


install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- make test-api-detached
- timeout 60 bash -c 'while ! nc -z localhost 8080; do sleep 0.1; done'
- stack --no-terminal test --haddock --no-haddock-deps --ghc-options=-Werror
