name:                flatbuffers
version:             0.3.0.0
homepage:            https://github.com/dcastro/haskell-flatbuffers
github:              dcastro/haskell-flatbuffers
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2019 Diogo Castro
category:            Data, Serialization, Network
tested-with:
    GHC == 8.4.3
  , GHC == 8.6.5

synopsis:            Haskell implementation of the FlatBuffers protocol.
description: |
  Haskell implementation of the FlatBuffers protocol.

  See the GitHub page for documentation: <https://github.com/dcastro/haskell-flatbuffers>

extra-source-files:
  - README.md
  - CHANGELOG.md

extra-doc-files:
  - README.md

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wincomplete-record-updates
  - -Wredundant-constraints

dependencies:
  - base >= 4.11 && < 5
  - bytestring >= 0.10.8.0
  - text >= 1.2.3.0
  - mtl >= 2.2.1
  - containers >= 0.5.11.0
  - megaparsec >= 7.0
  - parser-combinators >= 1.0
  - binary >= 0.8.4.0
  - scientific >= 0.3.5.2
  - template-haskell >= 2.13.0.0
  - filepath >= 1.4.2
  - directory >= 1.3.1.2
  - text-manipulate >= 0.1.0
  - mono-traversable >= 1.0.1.2

default-extensions:
  - TypeOperators

library:
  source-dirs:      src

tests:
  test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
    - flatbuffers
    - hspec
    - hspec-core
    - hspec-expectations-pretty-diff
    - HUnit
    - hspec-megaparsec
    - hedgehog
    - hw-hspec-hedgehog
    - http-client
    - http-types
    - aeson
    - aeson-pretty
    - raw-strings-qq
    - utf8-string
    - process
    # - th-pprint
    - pretty-simple

benchmarks:
  criterion-bench:
    main: Main.hs
    source-dirs: bench/
    dependencies:
      - flatbuffers
      - criterion
      - vector
      - aeson
    ghc-options:
      - -threaded
      - -rtsopts
