name:                flatbuffers
version:             0.3.0.0
homepage:            https://github.com/dcastro/haskell-flatbuffers
github:              dcastro/haskell-flatbuffers
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2019 Diogo Castro
category:            Data, Serialization, Network
tested-with:
    GHC == 9.2.5
  , GHC == 9.4.8

synopsis:            Haskell implementation of the FlatBuffers protocol.
description: |
  Haskell implementation of the FlatBuffers protocol.

  See the GitHub page for documentation: <https://github.com/dcastro/haskell-flatbuffers>

extra-source-files:
  - README.md
  - CHANGELOG.md

extra-doc-files:
  - README.md

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wincomplete-record-updates
  - -Wredundant-constraints

dependencies:
  - base >= 4.16 && < 5
  - bytestring >= 0.11.3.1
  - text >= 2.0
  - mtl >= 2.2.2
  - containers >= 0.6.4.1
  - megaparsec >= 9.2.2
  - parser-combinators >= 1.3.0
  - binary >= 0.8.9.0
  - scientific >= 0.3.7.0
  - template-haskell >= 2.18.0.0
  - filepath >= 1.4.2.2
  - directory >= 1.3.6.2
  - text-manipulate >= 0.3.1.0
  - mono-traversable >= 1.0.15.3

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - DeriveTraversable
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - NegativeLiterals
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

library:
  source-dirs:      src

tests:
  test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
    - flatbuffers
    - hspec
    - hspec-core
    - hspec-expectations-pretty-diff
    - HUnit
    - hspec-megaparsec
    - hedgehog
    - hspec-hedgehog
    - http-client
    - http-types
    - aeson
    - aeson-pretty
    - raw-strings-qq
    - utf8-string
    - process
    - pretty-simple
    - hex-text

benchmarks:
  criterion-bench:
    main: Main.hs
    source-dirs: bench/
    dependencies:
      - flatbuffers
      - criterion
      - vector
      - aeson
    ghc-options:
      - -threaded
      - -rtsopts
